<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePersonalTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('personal', function (Blueprint $table) {
            $table->id();
            $table->string('cedula');
            $table->string('apellido1')->nullable();
            $table->string('apellido2')->nullable();
            $table->string('nombres')->nullable();
            $table->enum('genero',['M','F']);
            $table->bigIncrements('idtipo_documento');
            $table->bigIncrements('idtipo_nacionalidad');
            $table->bigIncrements('idtipo_genero');
            $table->bigIncrements('idtipo_estado_civil');
            $table->bigIncrements('idtipo_etnia');
            $table->bigIncrements('idtipo_nacionalidad_indigena');
            $table->bigIncrements('idtipo_sangre');
            $table->bigIncrements('idtipo_pais_origen');
            $table->bigIncrements('idtipo_provincia_origen');
            $table->bigIncrements('idtipo_canton_origen');
            $table->bigIncrements('idtipo_parroquia_origen');
            $table->bigIncrements('idtipo_pais_residencia');
            $table->bigIncrements('idtipo_provincia_residencia');
            $table->bigIncrements('idtipo_canton_residencia');
            $table->bigIncrements('idtipo_parroquia_residencia');
            $table->bigIncrements('residencia_anios')->nullable();
            $table->string('numero_libreta_militar')->nullable();
            $table->date('fecha_nacimiento')->nullable();
            $table->string('discapacidad_numero_carne')->nullable();
            $table->bigIncrements('discapacidad_numero_porcentaje')->nullable();
            $table->bigIncrements('idtipo_discapacidad');
            $table->string('residencia_calle_1')->nullable();
            $table->string('residencia_calle_2')->nullable();
            $table->string('residencia_calle_3')->nullable();
            $table->string('residencia_referencia')->nullable();
            $table->string('residencia_domicilio_numero')->nullable();
            $table->string('telefono_personal_domicilio')->nullable();
            $table->string('telefono_personal_celular')->nullable();
            $table->string('telefono_personal_trabajo')->nullable();
            $table->string('telefono_personal_extension')->nullable();
            $table->string('correo_personal_institucional')->nullable();
            $table->string('contacto_emergencia_apellidos')->nullable();
            $table->string('contacto_emergencia_nombres')->nullable();
            $table->string('contacto_emergencia_telefono_1')->nullable();
            $table->string('contacto_emergencia_telefono_2')->nullable();
            $table->bigIncrements('salario_mensual_f_total')->nullable();
            $table->bigIncrements('salario_mensual_f_integrantes');
            $table->bigIncrements('idtipo_relacion_conyuge');
            $table->bigIncrements('idtipo_documento_conyuge');
            $table->string('conyuge_cedula')->nullable();
            $table->string('conyuge_apellido_1')->nullable();
            $table->string('conyuge_apellido_2')->nullable();
            $table->string('conyuge_nombres')->nullable();
            $table->bigIncrements('idfichero_hoja_vida_foto')->nullable();
            $table->bigIncrements('idfichero_hoja_vida_cedula')->nullable();
            $table->bigIncrements('idfichero_hoja_vida_certificado_votacion')->nullable();
            $table->string('estudiante_apellido_1_madre')->nullable();
            $table->string('estudiante_apellido_2_madre')->nullable();
            $table->string('estudiante_nombres_madre')->nullable();
            $table->string('estudiante_apellido_1_padre')->nullable();
            $table->string('estudiante_apellido_2_padre')->nullable();
            $table->string('estudiante_nombres_padre')->nullable();
            $table->string('discapacidad_observacion')->nullable();
            $table->enum('discapacidad_validada',['S','N']);
            $table->bigIncrements('idtipo_beca');
            $table->string('o_beca')->nullable();
            $table->string('snna_codigo_unico')->nullable();
            $table->date('snna_fecha_inscripcion')->nullable();
            $table->float('snna_puntaje')->nullable();
            $table->bigIncrements('idtipo_internet_dispone');
            $table->bigIncrements('idtipo_celular_dispone');
            $table->bigIncrements('internet_horas_uso')->nullable();
            $table->bigIncrements('red_social_horas_uso')->nullable();
            $table->string('tipo_red_social_utiliza')->nullable();
            $table->string('tipo_tecnologia_utiliza')->nullable();
            $table->float('transporte_horas_traslado')->nullable();
            $table->float('transporte_horas_permanencia')->nullable();
            $table->bigIncrements('idtipo_transporte');
            $table->bigIncrements('hijos_numero');
            $table->bigIncrements('hijos_edad');
            $table->bigIncrements('idtipo_vivienda');
            $table->bigIncrements('idtipo_vivienda_localizacion');
            $table->bigIncrements('idtipo_jefe_f_nivel_instruccion');
            $table->bigIncrements('idtipo_salario_mensual_f_total');
            $table->bigIncrements('idtipo_jefe_ocupacion');
            $table->bigIncrements('idtipo_estudiante_ocupacion');
            $table->string('tipo_solvencia')->nullable();
            $table->string('valor_terremoto')->nullable();
            $table->integer('dato_vivienda');
            $table->integer('tipo_vivienda');
            $table->string('afectada_terremoto_obser')->nullable();
            $table->integer('afectado_lugar');
            $table->string('afectado_ocupacion_padre')->nullable();
            $table->string('afectado_ocupacion_madre')->nullable();
            $table->string('afectacion_perdio_padre')->nullable();
            $table->string('afectacion_perdio_madre')->nullable();
            $table->enum('act_terremoto',['S','N']);
            $table->integer('afectada_terremoto');
            $table->string('tiene_enfermedad')->nullable();
            $table->string('tiene_padres_enfermedad')->nullable();
            $table->integer('tiene_interes_estudiar')->nullable();
            $table->enum('estado_usuario',['S','N']);
            $table->integer('accesos_fallidos');
            $table->enum('bloqueado',['S','N']);
            $table->enum('password_changed',['S','N']);
            $table->enum('act_sniese',['S','N']);
            $table->timestamp('fecha_ultima_actualizacion');
            $table->integer('logueado')->nullable();
            $table->timestamp('fecha_ultimo_ingreso')->nullable();
            $table->integer('documento_original');
            $table->string('datos_actualizados')->nullable();
            $table->string('datos_especifique')->nullable();
            $table->enum('datos_estado',['S','N'])->nullable();
            $table->bigIncrements('idtipo_parquadero_auto');
            $table->bigIncrements('idtipo_parquadero_bici');
            $table->string('problema_aprendizaje')->nullable();
            $table->string('problema_aprendizaje_otros')->nullable();
            $table->date('discapacidad_fecha')->nullable();
            $table->string('pasaporte')->nullable();
            $table->json('json_habito_estudio')->nullable();
            $table->json('json_caracteristica_personalidad')->nullable();
            $table->json('json_ambiente_familiar')->nullable();
            $table->json('json_composicion_familiar')->nullable();
            $table->json('json_ingreso_universidad')->nullable();
            $table->boolean('hv_verificada');
            $table->bigIncrements('idtipo_pais_trabajo');
            $table->bigIncrements('idtipo_provincia_trabajo');
            $table->bigIncrements('idtipo_canton_trabajo');
            $table->bigIncrements('idtipo_parroquia_trabajo');
            $table->bigIncrements('idtipo_contacto_familiar');
            $table->bigIncrements('idtipo_documento_familiar');
            $table->string('familiar_cedula')->nullable();
            $table->string('familiar_apellido_1')->nullable();
            $table->string('familiar_apellido_2')->nullable();
            $table->string('familiar_nombres')->nullable();
            $table->string('control_asistencia');
            $table->timestamp('fecha_registro');
            $table->bigIncrements('idtipo_nivel_instruccion');
            $table->json('json_problemas_salud')->nullable();
            $table->json('json_problemas_aprendizaje')->nullable();
            $table->boolean('esijef');
            $table->boolean('esijef2');
            $table->string('idnumber_moodle')->nullable();
            $table->string('escala_ocupacional')->nullable();
            $table->string('denominacion_puesto')->nullable();
            $table->string('unidad_organica')->nullable();
            $table->integer('trabajador_activo');
            $table->enum('esta_embarazada',['S','N']);
            $table->integer('lactante_edad')->nullable();
            $table->bigIncrements('idtipo_bloque_tutoria');
            $table->bigIncrements('idtipo_orientacion_sexual');
            $table->bigIncrements('idtipo_preferencia_religiosa');
            $table->string('r_direccion');
            $table->bigIncrements('idtipo_r_construccion');
            $table->bigIncrements('idtipo_r_tipo_vivienda');
            $table->bigIncrements('idtipo_r_financiamiento');
            $table->string('r_servicio_basico')->nullable();
            $table->bigIncrements('idtipo_r_gasto_alquiler');
            $table->bigIncrements('idtipo_madre_instruccion');
            $table->bigIncrements('idtipo_padre_instruccion');
            $table->bigIncrements('idtipo_pareja_instruccion');
            $table->string('dificultad_estudios')->nullable();
            $table->bigIncrements('idtipo_gasto_transporte');
            $table->bigIncrements('idtipo_vivienda_financiamiento');
            $table->bigIncrements('idtipo_manutencion');
            $table->bigIncrements('idtipo_manutencion_alquiler');
            $table->bigIncrements('idtipo_gasto_alimentacion');
            $table->bigIncrements('idtipo_gasto_colegiatura');
            $table->string('reside_portoviejo')->nullable();
            $table->integer('integrante_bachillerato')->nullable();
            $table->integer('integrante_universidad')->nullable();
            $table->bigIncrements('idtipo_computador_dispone');
            $table->bigIncrements('idtipo_tablet_dispone');
            $table->bigIncrements('idtipo_internet_telefono_dispone');
            $table->bigIncrements('idtipo_clase_virtual_desea');
            $table->integer('salario_mensual_f_integrantes_ingreso');
            $table->bigIncrements('idfichero_hoja_vida_ruc')->nullable();
            $table->jsonb('terminos');
            $table->enum('foto_valida',['S','N']);
            $table->json('json_validar_foto')->nullable();
            $table->bigIncrements('idfichero_hoja_vida_foto_tmp');
            $table->jsonb('json_control');
            $table->jsonb('json_vacuna_covid');
            $table->enum('vacunado_covid',['S','N','X']);
            $table->date('fecha_encuesta_vacuna')->nullable();


        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('personal');
    }
}
